[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = [ ".cache" ]

[[headers]]
  for = "/assets/fonts/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/images/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/error/"
  status = 200
